#ifndef SNAKEMAN_STATE_H
#define SNAKEMAN_STATE_H

typedef enum {
    GAME_STATE_BOOT = 0,
    GAME_STATE_TITLE,
    GAME_STATE_RUNNING,
    GAME_STATE_PAUSED,
    GAME_STATE_GAME_OVER,
    GAME_STATE_HIGHSCORES,
    GAME_STATE_QUIT
} GameState;

typedef enum {
    TRANSITION_EVENT_NONE = 0,
    TRANSITION_EVENT_START,
    TRANSITION_EVENT_PAUSE,
    TRANSITION_EVENT_RESUME,
    TRANSITION_EVENT_BACK_TO_TITLE,
    TRANSITION_EVENT_PLAYER_DIED,
    TRANSITION_EVENT_RUN_COMPLETE,
    TRANSITION_EVENT_SHOW_HIGHSCORES,
    TRANSITION_EVENT_RESTART,
    TRANSITION_EVENT_QUIT
} TransitionEvent;

GameState state_next(GameState current, TransitionEvent event);

#endif
