#include "test_framework.h"

#include "snakeman/state.h"

void test_state_transition_map_matches_design(void) {
    ASSERT_EQ_INT(state_next(GAME_STATE_BOOT, TRANSITION_EVENT_NONE), GAME_STATE_TITLE);
    ASSERT_EQ_INT(state_next(GAME_STATE_BOOT, TRANSITION_EVENT_QUIT), GAME_STATE_QUIT);

    ASSERT_EQ_INT(state_next(GAME_STATE_TITLE, TRANSITION_EVENT_START), GAME_STATE_RUNNING);
    ASSERT_EQ_INT(state_next(GAME_STATE_TITLE, TRANSITION_EVENT_QUIT), GAME_STATE_QUIT);

    ASSERT_EQ_INT(state_next(GAME_STATE_RUNNING, TRANSITION_EVENT_PAUSE), GAME_STATE_PAUSED);
    ASSERT_EQ_INT(state_next(GAME_STATE_RUNNING, TRANSITION_EVENT_PLAYER_DIED), GAME_STATE_GAME_OVER);
    ASSERT_EQ_INT(state_next(GAME_STATE_RUNNING, TRANSITION_EVENT_RUN_COMPLETE), GAME_STATE_HIGHSCORES);
    ASSERT_EQ_INT(state_next(GAME_STATE_RUNNING, TRANSITION_EVENT_QUIT), GAME_STATE_QUIT);

    ASSERT_EQ_INT(state_next(GAME_STATE_PAUSED, TRANSITION_EVENT_RESUME), GAME_STATE_RUNNING);
    ASSERT_EQ_INT(state_next(GAME_STATE_PAUSED, TRANSITION_EVENT_BACK_TO_TITLE), GAME_STATE_TITLE);
    ASSERT_EQ_INT(state_next(GAME_STATE_PAUSED, TRANSITION_EVENT_QUIT), GAME_STATE_QUIT);

    ASSERT_EQ_INT(state_next(GAME_STATE_GAME_OVER, TRANSITION_EVENT_SHOW_HIGHSCORES), GAME_STATE_HIGHSCORES);
    ASSERT_EQ_INT(state_next(GAME_STATE_GAME_OVER, TRANSITION_EVENT_QUIT), GAME_STATE_QUIT);

    ASSERT_EQ_INT(state_next(GAME_STATE_HIGHSCORES, TRANSITION_EVENT_RESTART), GAME_STATE_RUNNING);
    ASSERT_EQ_INT(state_next(GAME_STATE_HIGHSCORES, TRANSITION_EVENT_BACK_TO_TITLE), GAME_STATE_TITLE);
    ASSERT_EQ_INT(state_next(GAME_STATE_HIGHSCORES, TRANSITION_EVENT_QUIT), GAME_STATE_QUIT);
}

void test_state_invalid_events_are_noop(void) {
    ASSERT_EQ_INT(state_next(GAME_STATE_TITLE, TRANSITION_EVENT_PAUSE), GAME_STATE_TITLE);
    ASSERT_EQ_INT(state_next(GAME_STATE_RUNNING, TRANSITION_EVENT_RESUME), GAME_STATE_RUNNING);
    ASSERT_EQ_INT(state_next(GAME_STATE_PAUSED, TRANSITION_EVENT_START), GAME_STATE_PAUSED);
    ASSERT_EQ_INT(state_next(GAME_STATE_GAME_OVER, TRANSITION_EVENT_START), GAME_STATE_GAME_OVER);
    ASSERT_EQ_INT(state_next(GAME_STATE_HIGHSCORES, TRANSITION_EVENT_PAUSE), GAME_STATE_HIGHSCORES);
}

void test_state_quit_is_terminal(void) {
    ASSERT_EQ_INT(state_next(GAME_STATE_QUIT, TRANSITION_EVENT_NONE), GAME_STATE_QUIT);
    ASSERT_EQ_INT(state_next(GAME_STATE_QUIT, TRANSITION_EVENT_START), GAME_STATE_QUIT);
    ASSERT_EQ_INT(state_next(GAME_STATE_QUIT, TRANSITION_EVENT_PLAYER_DIED), GAME_STATE_QUIT);
    ASSERT_EQ_INT(state_next(GAME_STATE_QUIT, TRANSITION_EVENT_QUIT), GAME_STATE_QUIT);
}
