#include "test_framework.h"

/* ---- test_state.c ---- */
void test_boot_goes_to_title(void);
void test_running_fatal_event_priority(void);
void test_highscores_restart_goes_running(void);

/* ---- test_state_spec.c ---- */
void test_state_transition_map_matches_design(void);
void test_state_invalid_events_are_noop(void);
void test_state_quit_is_terminal(void);

/* ---- test_state_extended.c ---- */
void test_state_boot_none_goes_title(void);
void test_state_boot_start_is_noop(void);
void test_state_boot_pause_is_noop(void);
void test_state_boot_resume_is_noop(void);
void test_state_boot_back_to_title_is_noop(void);
void test_state_boot_player_died_is_noop(void);
void test_state_boot_run_complete_is_noop(void);
void test_state_boot_show_highscores_is_noop(void);
void test_state_boot_restart_is_noop(void);
void test_state_boot_quit_goes_quit(void);
void test_state_title_none_stays_title(void);
void test_state_title_start_goes_running(void);
void test_state_title_pause_is_noop(void);
void test_state_title_resume_is_noop(void);
void test_state_title_back_to_title_is_noop(void);
void test_state_title_player_died_is_noop(void);
void test_state_title_run_complete_is_noop(void);
void test_state_title_show_highscores_is_noop(void);
void test_state_title_restart_is_noop(void);
void test_state_title_quit_goes_quit(void);
void test_state_running_none_stays_running(void);
void test_state_running_start_is_noop(void);
void test_state_running_pause_goes_paused(void);
void test_state_running_resume_is_noop(void);
void test_state_running_back_to_title_is_noop(void);
void test_state_running_player_died_goes_game_over(void);
void test_state_running_run_complete_goes_highscores(void);
void test_state_running_show_highscores_is_noop(void);
void test_state_running_restart_is_noop(void);
void test_state_running_quit_goes_quit(void);
void test_state_paused_none_stays_paused(void);
void test_state_paused_start_is_noop(void);
void test_state_paused_pause_is_noop(void);
void test_state_paused_resume_goes_running(void);
void test_state_paused_back_to_title_goes_title(void);
void test_state_paused_player_died_is_noop(void);
void test_state_paused_run_complete_is_noop(void);
void test_state_paused_show_highscores_is_noop(void);
void test_state_paused_restart_is_noop(void);
void test_state_paused_quit_goes_quit(void);
void test_state_game_over_none_stays_game_over(void);
void test_state_game_over_start_is_noop(void);
void test_state_game_over_pause_is_noop(void);
void test_state_game_over_resume_is_noop(void);
void test_state_game_over_back_to_title_is_noop(void);
void test_state_game_over_player_died_is_noop(void);
void test_state_game_over_run_complete_is_noop(void);
void test_state_game_over_show_highscores_goes_highscores(void);
void test_state_game_over_restart_is_noop(void);
void test_state_game_over_quit_goes_quit(void);
void test_state_highscores_none_stays_highscores(void);
void test_state_highscores_start_is_noop(void);
void test_state_highscores_pause_is_noop(void);
void test_state_highscores_resume_is_noop(void);
void test_state_highscores_back_to_title_goes_title(void);
void test_state_highscores_player_died_is_noop(void);
void test_state_highscores_run_complete_is_noop(void);
void test_state_highscores_show_highscores_is_noop(void);
void test_state_highscores_restart_goes_running(void);
void test_state_highscores_quit_goes_quit(void);
void test_state_quit_none_stays_quit(void);
void test_state_quit_start_stays_quit(void);
void test_state_quit_pause_stays_quit(void);
void test_state_quit_resume_stays_quit(void);
void test_state_quit_back_to_title_stays_quit(void);
void test_state_quit_player_died_stays_quit(void);
void test_state_quit_run_complete_stays_quit(void);
void test_state_quit_show_highscores_stays_quit(void);
void test_state_quit_restart_stays_quit(void);
void test_state_quit_quit_stays_quit(void);
void test_state_full_play_cycle(void);
void test_state_play_pause_resume_cycle(void);
void test_state_paused_back_to_title_restart_cycle(void);
void test_state_highscores_back_to_title_cycle(void);
void test_state_win_flow_running_to_highscores(void);
void test_state_quit_from_every_non_boot_state(void);
void test_state_death_priority_over_pause(void);
void test_state_run_complete_priority_over_pause(void);
void test_state_idempotence_none_event(void);
void test_state_repeated_pause_resume(void);

/* ---- test_scoring.c ---- */
void test_pickup_increases_score_and_count(void);
void test_combo_expires_back_to_one(void);
void test_highscore_insert_orders_descending(void);

/* ---- test_scoring_spec.c ---- */
void test_score_init_matches_design_defaults(void);
void test_pickup_refreshes_combo_timer_to_default(void);
void test_pickup_uses_multiplier_before_increment(void);
void test_combo_multiplier_caps_at_four(void);
void test_combo_expires_exactly_at_boundary(void);
void test_combo_remains_active_before_window_ends(void);
void test_survival_event_adds_score_and_seconds(void);
void test_magnet_pickup_adds_flat_bonus(void);
void test_risk_bonus_is_fifty_percent_of_pickup_value_spec(void);
void test_score_finalize_run_snapshots_fields(void);
void test_highscore_init_clears_all_entries(void);
void test_highscore_insert_shifts_and_returns_rank(void);
void test_highscore_rejects_when_score_not_high_enough(void);
void test_highscore_accepts_rank_nine_boundary(void);

/* ---- test_scoring_extended.c ---- */
void test_score_init_null_pointer_is_safe(void);
void test_score_init_combo_timer_starts_at_zero(void);
void test_score_init_multiplier_starts_at_one(void);
void test_score_init_can_be_called_twice_safely(void);
void test_score_update_null_pointer_is_safe(void);
void test_score_update_zero_dt_is_noop(void);
void test_score_update_negative_dt_is_noop(void);
void test_score_update_no_active_timer_is_safe(void);
void test_score_update_timer_decreases_by_dt(void);
void test_score_update_timer_clamps_to_zero(void);
void test_score_update_multiplier_resets_on_expire(void);
void test_score_update_multiplier_preserved_if_timer_active(void);
void test_score_update_multiple_small_steps_equivalent(void);
void test_score_on_event_null_pointer_is_safe(void);
void test_score_on_event_none_is_noop(void);
void test_pickup_first_awards_base_ten(void);
void test_pickup_second_awards_at_125x(void);
void test_pickup_third_awards_at_150x(void);
void test_pickup_fourth_awards_at_175x(void);
void test_pickup_increments_count_correctly(void);
void test_pickup_at_max_multiplier_scores_40(void);
void test_combo_multiplier_increments_025_per_pickup(void);
void test_combo_multiplier_does_not_exceed_cap(void);
void test_combo_cap_exactly_at_13th_pickup(void);
void test_combo_timer_refreshes_on_every_pickup(void);
void test_combo_multiplier_reset_then_rebuild(void);
void test_max_combo_multiplier_tracks_highest(void);
void test_max_combo_never_decreases(void);
void test_combo_timer_just_barely_active(void);
void test_combo_timer_exact_expire_resets_multiplier(void);
void test_combo_timer_slightly_past_expire(void);
void test_combo_timer_does_not_go_negative(void);
void test_survival_single_tick(void);
void test_survival_multiple_ticks(void);
void test_survival_does_not_affect_combo(void);
void test_survival_does_not_affect_pickup_count(void);
void test_magnet_pickup_awards_flat_five(void);
void test_magnet_pickup_does_not_affect_combo(void);
void test_magnet_pickup_does_not_affect_pickup_count(void);
void test_magnet_pickup_stacks_with_regular_score(void);
void test_magnet_pickup_multiple_awards_stack(void);
void test_risk_pickup_awards_flat_five(void);
void test_risk_pickup_does_not_affect_combo(void);
void test_risk_pickup_does_not_affect_pickup_count(void);
void test_risk_pickup_stacks_with_regular_pickup(void);
void test_mixed_events_survival_and_pickups(void);
void test_mixed_events_all_types(void);
void test_long_scoring_session(void);
void test_combo_interleave_pickup_and_decay(void);
void test_combo_decay_across_multiple_expire_cycles(void);
void test_finalize_run_null_pointer_returns_defaults(void);
void test_finalize_run_captures_score(void);
void test_finalize_run_captures_pickups(void);
void test_finalize_run_captures_max_combo(void);
void test_finalize_run_captures_seed(void);
void test_finalize_run_captures_time(void);
void test_finalize_run_with_zero_score(void);
void test_score_accumulation_exact_sequence(void);

/* ---- test_highscore_extended.c ---- */
void test_highscore_init_null_pointer_is_safe(void);
void test_highscore_init_all_fields_zero(void);
void test_highscore_init_can_be_called_twice(void);
void test_highscore_insert_null_pointer_returns_neg(void);
void test_highscore_insert_single_entry_rank_zero(void);
void test_highscore_insert_two_ascending_order(void);
void test_highscore_insert_two_descending_order(void);
void test_highscore_insert_three_mixed_order(void);
void test_highscore_full_table_fill_ten(void);
void test_highscore_full_table_reject_lower_score(void);
void test_highscore_full_table_reject_equal_to_lowest(void);
void test_highscore_full_table_insert_beats_lowest(void);
void test_highscore_full_table_insert_new_top(void);
void test_highscore_full_table_insert_middle(void);
void test_highscore_shift_preserves_all_fields(void);
void test_highscore_eviction_drops_rank_ten(void);
void test_highscore_insert_identical_scores(void);
void test_highscore_insert_same_score_when_full(void);
void test_highscore_insert_slightly_above_all_same(void);
void test_highscore_insert_ranks_fill_sequentially(void);
void test_highscore_insert_ranks_ascending_order(void);
void test_highscore_insert_zero_score_into_empty(void);
void test_highscore_insert_one_point_into_empty(void);
void test_highscore_stress_100_inserts(void);
void test_highscore_stress_100_descending_inserts(void);
void test_highscore_stress_alternating_inserts(void);
void test_highscore_invariant_sorted_descending(void);

/* ---- test_game_spec.c ---- */
void test_game_init_sets_title_and_resets_counters(void);
void test_game_title_start_enters_running_and_steps_simulation(void);
void test_game_quit_input_has_priority(void);
void test_game_running_pause_freezes_simulation(void);
void test_game_paused_resume_reenters_running(void);
void test_game_survival_points_increment_once_per_second(void);
void test_game_survival_awards_multiple_seconds_for_large_dt_spec(void);
void test_game_pause_freezes_score_timers(void);
void test_game_over_screen_has_minimum_lock_before_highscores_spec(void);

/* ---- test_game_extended.c ---- */
void test_game_init_null_game_is_safe(void);
void test_game_init_null_config_is_safe(void);
void test_game_init_state_is_title(void);
void test_game_init_tick_count_zero(void);
void test_game_init_run_time_zero(void);
void test_game_init_fixed_steps_zero(void);
void test_game_init_second_fraction_zero(void);
void test_game_init_score_state_zeroed(void);
void test_game_init_highscore_table_zeroed(void);
void test_game_init_can_be_called_multiple_times(void);
void test_game_update_null_game_is_safe(void);
void test_game_update_null_input_is_safe(void);
void test_game_update_zero_dt_is_noop(void);
void test_game_update_negative_dt_is_noop(void);
void test_game_title_to_running_via_start(void);
void test_game_title_to_running_via_restart(void);
void test_game_title_to_quit(void);
void test_game_title_no_input_stays_title(void);
void test_game_running_to_paused(void);
void test_game_paused_to_running_via_resume(void);
void test_game_paused_to_running_via_pause_toggle(void);
void test_game_running_quit_from_running(void);
void test_game_paused_quit(void);
void test_game_quit_priority_over_start(void);
void test_game_quit_priority_over_pause(void);
void test_game_quit_priority_over_resume(void);
void test_game_quit_priority_over_restart(void);
void test_game_ticks_advance_in_running(void);
void test_game_ticks_frozen_in_title(void);
void test_game_ticks_frozen_in_paused(void);
void test_game_fixed_steps_track_ticks(void);
void test_game_second_fraction_accumulates(void);
void test_game_second_fraction_wraps_at_one(void);
void test_game_survival_point_awarded_at_one_second(void);
void test_game_no_survival_point_before_one_second(void);
void test_game_survival_accumulates_over_time(void);
void test_game_pause_freezes_tick_count(void);
void test_game_pause_freezes_second_fraction(void);
void test_game_pause_freezes_run_time(void);
void test_game_pause_freezes_combo_timer(void);
void test_game_resume_continues_from_paused_state(void);
void test_game_combo_timer_ticks_down_in_running(void);
void test_game_combo_expires_during_running(void);
void test_game_game_over_auto_transitions_to_highscores(void);
void test_game_highscores_restart_enters_running(void);
void test_game_highscores_start_enters_running(void);
void test_game_highscores_quit(void);
void test_game_highscores_no_input_stays(void);
void test_game_game_over_start_shows_highscores(void);
void test_game_game_over_restart_shows_highscores(void);
void test_game_game_over_quit(void);
void test_game_full_lifecycle_title_run_die_highscores_restart(void);
void test_game_full_lifecycle_title_run_pause_quit(void);
void test_game_quit_is_terminal(void);
void test_game_no_simulation_in_quit(void);
void test_input_direction_enum_values(void);
void test_game_rapid_start_pause_resume(void);
void test_game_multiple_no_input_updates(void);

int main(void) {
    /* ========== State Machine: Original ========== */
    RUN_TEST(test_boot_goes_to_title);
    RUN_TEST(test_running_fatal_event_priority);
    RUN_TEST(test_highscores_restart_goes_running);
    RUN_TEST(test_state_transition_map_matches_design);
    RUN_TEST(test_state_invalid_events_are_noop);
    RUN_TEST(test_state_quit_is_terminal);

    /* ========== State Machine: Extended ========== */
    RUN_TEST(test_state_boot_none_goes_title);
    RUN_TEST(test_state_boot_start_is_noop);
    RUN_TEST(test_state_boot_pause_is_noop);
    RUN_TEST(test_state_boot_resume_is_noop);
    RUN_TEST(test_state_boot_back_to_title_is_noop);
    RUN_TEST(test_state_boot_player_died_is_noop);
    RUN_TEST(test_state_boot_run_complete_is_noop);
    RUN_TEST(test_state_boot_show_highscores_is_noop);
    RUN_TEST(test_state_boot_restart_is_noop);
    RUN_TEST(test_state_boot_quit_goes_quit);
    RUN_TEST(test_state_title_none_stays_title);
    RUN_TEST(test_state_title_start_goes_running);
    RUN_TEST(test_state_title_pause_is_noop);
    RUN_TEST(test_state_title_resume_is_noop);
    RUN_TEST(test_state_title_back_to_title_is_noop);
    RUN_TEST(test_state_title_player_died_is_noop);
    RUN_TEST(test_state_title_run_complete_is_noop);
    RUN_TEST(test_state_title_show_highscores_is_noop);
    RUN_TEST(test_state_title_restart_is_noop);
    RUN_TEST(test_state_title_quit_goes_quit);
    RUN_TEST(test_state_running_none_stays_running);
    RUN_TEST(test_state_running_start_is_noop);
    RUN_TEST(test_state_running_pause_goes_paused);
    RUN_TEST(test_state_running_resume_is_noop);
    RUN_TEST(test_state_running_back_to_title_is_noop);
    RUN_TEST(test_state_running_player_died_goes_game_over);
    RUN_TEST(test_state_running_run_complete_goes_highscores);
    RUN_TEST(test_state_running_show_highscores_is_noop);
    RUN_TEST(test_state_running_restart_is_noop);
    RUN_TEST(test_state_running_quit_goes_quit);
    RUN_TEST(test_state_paused_none_stays_paused);
    RUN_TEST(test_state_paused_start_is_noop);
    RUN_TEST(test_state_paused_pause_is_noop);
    RUN_TEST(test_state_paused_resume_goes_running);
    RUN_TEST(test_state_paused_back_to_title_goes_title);
    RUN_TEST(test_state_paused_player_died_is_noop);
    RUN_TEST(test_state_paused_run_complete_is_noop);
    RUN_TEST(test_state_paused_show_highscores_is_noop);
    RUN_TEST(test_state_paused_restart_is_noop);
    RUN_TEST(test_state_paused_quit_goes_quit);
    RUN_TEST(test_state_game_over_none_stays_game_over);
    RUN_TEST(test_state_game_over_start_is_noop);
    RUN_TEST(test_state_game_over_pause_is_noop);
    RUN_TEST(test_state_game_over_resume_is_noop);
    RUN_TEST(test_state_game_over_back_to_title_is_noop);
    RUN_TEST(test_state_game_over_player_died_is_noop);
    RUN_TEST(test_state_game_over_run_complete_is_noop);
    RUN_TEST(test_state_game_over_show_highscores_goes_highscores);
    RUN_TEST(test_state_game_over_restart_is_noop);
    RUN_TEST(test_state_game_over_quit_goes_quit);
    RUN_TEST(test_state_highscores_none_stays_highscores);
    RUN_TEST(test_state_highscores_start_is_noop);
    RUN_TEST(test_state_highscores_pause_is_noop);
    RUN_TEST(test_state_highscores_resume_is_noop);
    RUN_TEST(test_state_highscores_back_to_title_goes_title);
    RUN_TEST(test_state_highscores_player_died_is_noop);
    RUN_TEST(test_state_highscores_run_complete_is_noop);
    RUN_TEST(test_state_highscores_show_highscores_is_noop);
    RUN_TEST(test_state_highscores_restart_goes_running);
    RUN_TEST(test_state_highscores_quit_goes_quit);
    RUN_TEST(test_state_quit_none_stays_quit);
    RUN_TEST(test_state_quit_start_stays_quit);
    RUN_TEST(test_state_quit_pause_stays_quit);
    RUN_TEST(test_state_quit_resume_stays_quit);
    RUN_TEST(test_state_quit_back_to_title_stays_quit);
    RUN_TEST(test_state_quit_player_died_stays_quit);
    RUN_TEST(test_state_quit_run_complete_stays_quit);
    RUN_TEST(test_state_quit_show_highscores_stays_quit);
    RUN_TEST(test_state_quit_restart_stays_quit);
    RUN_TEST(test_state_quit_quit_stays_quit);
    RUN_TEST(test_state_full_play_cycle);
    RUN_TEST(test_state_play_pause_resume_cycle);
    RUN_TEST(test_state_paused_back_to_title_restart_cycle);
    RUN_TEST(test_state_highscores_back_to_title_cycle);
    RUN_TEST(test_state_win_flow_running_to_highscores);
    RUN_TEST(test_state_quit_from_every_non_boot_state);
    RUN_TEST(test_state_death_priority_over_pause);
    RUN_TEST(test_state_run_complete_priority_over_pause);
    RUN_TEST(test_state_idempotence_none_event);
    RUN_TEST(test_state_repeated_pause_resume);

    /* ========== Scoring: Original ========== */
    RUN_TEST(test_pickup_increases_score_and_count);
    RUN_TEST(test_combo_expires_back_to_one);
    RUN_TEST(test_highscore_insert_orders_descending);
    RUN_TEST(test_score_init_matches_design_defaults);
    RUN_TEST(test_pickup_refreshes_combo_timer_to_default);
    RUN_TEST(test_pickup_uses_multiplier_before_increment);
    RUN_TEST(test_combo_multiplier_caps_at_four);
    RUN_TEST(test_combo_expires_exactly_at_boundary);
    RUN_TEST(test_combo_remains_active_before_window_ends);
    RUN_TEST(test_survival_event_adds_score_and_seconds);
    RUN_TEST(test_magnet_pickup_adds_flat_bonus);
    RUN_TEST(test_risk_bonus_is_fifty_percent_of_pickup_value_spec);
    RUN_TEST(test_score_finalize_run_snapshots_fields);
    RUN_TEST(test_highscore_init_clears_all_entries);
    RUN_TEST(test_highscore_insert_shifts_and_returns_rank);
    RUN_TEST(test_highscore_rejects_when_score_not_high_enough);
    RUN_TEST(test_highscore_accepts_rank_nine_boundary);

    /* ========== Scoring: Extended ========== */
    RUN_TEST(test_score_init_null_pointer_is_safe);
    RUN_TEST(test_score_init_combo_timer_starts_at_zero);
    RUN_TEST(test_score_init_multiplier_starts_at_one);
    RUN_TEST(test_score_init_can_be_called_twice_safely);
    RUN_TEST(test_score_update_null_pointer_is_safe);
    RUN_TEST(test_score_update_zero_dt_is_noop);
    RUN_TEST(test_score_update_negative_dt_is_noop);
    RUN_TEST(test_score_update_no_active_timer_is_safe);
    RUN_TEST(test_score_update_timer_decreases_by_dt);
    RUN_TEST(test_score_update_timer_clamps_to_zero);
    RUN_TEST(test_score_update_multiplier_resets_on_expire);
    RUN_TEST(test_score_update_multiplier_preserved_if_timer_active);
    RUN_TEST(test_score_update_multiple_small_steps_equivalent);
    RUN_TEST(test_score_on_event_null_pointer_is_safe);
    RUN_TEST(test_score_on_event_none_is_noop);
    RUN_TEST(test_pickup_first_awards_base_ten);
    RUN_TEST(test_pickup_second_awards_at_125x);
    RUN_TEST(test_pickup_third_awards_at_150x);
    RUN_TEST(test_pickup_fourth_awards_at_175x);
    RUN_TEST(test_pickup_increments_count_correctly);
    RUN_TEST(test_pickup_at_max_multiplier_scores_40);
    RUN_TEST(test_combo_multiplier_increments_025_per_pickup);
    RUN_TEST(test_combo_multiplier_does_not_exceed_cap);
    RUN_TEST(test_combo_cap_exactly_at_13th_pickup);
    RUN_TEST(test_combo_timer_refreshes_on_every_pickup);
    RUN_TEST(test_combo_multiplier_reset_then_rebuild);
    RUN_TEST(test_max_combo_multiplier_tracks_highest);
    RUN_TEST(test_max_combo_never_decreases);
    RUN_TEST(test_combo_timer_just_barely_active);
    RUN_TEST(test_combo_timer_exact_expire_resets_multiplier);
    RUN_TEST(test_combo_timer_slightly_past_expire);
    RUN_TEST(test_combo_timer_does_not_go_negative);
    RUN_TEST(test_survival_single_tick);
    RUN_TEST(test_survival_multiple_ticks);
    RUN_TEST(test_survival_does_not_affect_combo);
    RUN_TEST(test_survival_does_not_affect_pickup_count);
    RUN_TEST(test_magnet_pickup_awards_flat_five);
    RUN_TEST(test_magnet_pickup_does_not_affect_combo);
    RUN_TEST(test_magnet_pickup_does_not_affect_pickup_count);
    RUN_TEST(test_magnet_pickup_stacks_with_regular_score);
    RUN_TEST(test_magnet_pickup_multiple_awards_stack);
    RUN_TEST(test_risk_pickup_awards_flat_five);
    RUN_TEST(test_risk_pickup_does_not_affect_combo);
    RUN_TEST(test_risk_pickup_does_not_affect_pickup_count);
    RUN_TEST(test_risk_pickup_stacks_with_regular_pickup);
    RUN_TEST(test_mixed_events_survival_and_pickups);
    RUN_TEST(test_mixed_events_all_types);
    RUN_TEST(test_long_scoring_session);
    RUN_TEST(test_combo_interleave_pickup_and_decay);
    RUN_TEST(test_combo_decay_across_multiple_expire_cycles);
    RUN_TEST(test_finalize_run_null_pointer_returns_defaults);
    RUN_TEST(test_finalize_run_captures_score);
    RUN_TEST(test_finalize_run_captures_pickups);
    RUN_TEST(test_finalize_run_captures_max_combo);
    RUN_TEST(test_finalize_run_captures_seed);
    RUN_TEST(test_finalize_run_captures_time);
    RUN_TEST(test_finalize_run_with_zero_score);
    RUN_TEST(test_score_accumulation_exact_sequence);

    /* ========== Highscore Table: Extended ========== */
    RUN_TEST(test_highscore_init_null_pointer_is_safe);
    RUN_TEST(test_highscore_init_all_fields_zero);
    RUN_TEST(test_highscore_init_can_be_called_twice);
    RUN_TEST(test_highscore_insert_null_pointer_returns_neg);
    RUN_TEST(test_highscore_insert_single_entry_rank_zero);
    RUN_TEST(test_highscore_insert_two_ascending_order);
    RUN_TEST(test_highscore_insert_two_descending_order);
    RUN_TEST(test_highscore_insert_three_mixed_order);
    RUN_TEST(test_highscore_full_table_fill_ten);
    RUN_TEST(test_highscore_full_table_reject_lower_score);
    RUN_TEST(test_highscore_full_table_reject_equal_to_lowest);
    RUN_TEST(test_highscore_full_table_insert_beats_lowest);
    RUN_TEST(test_highscore_full_table_insert_new_top);
    RUN_TEST(test_highscore_full_table_insert_middle);
    RUN_TEST(test_highscore_shift_preserves_all_fields);
    RUN_TEST(test_highscore_eviction_drops_rank_ten);
    RUN_TEST(test_highscore_insert_identical_scores);
    RUN_TEST(test_highscore_insert_same_score_when_full);
    RUN_TEST(test_highscore_insert_slightly_above_all_same);
    RUN_TEST(test_highscore_insert_ranks_fill_sequentially);
    RUN_TEST(test_highscore_insert_ranks_ascending_order);
    RUN_TEST(test_highscore_insert_zero_score_into_empty);
    RUN_TEST(test_highscore_insert_one_point_into_empty);
    RUN_TEST(test_highscore_stress_100_inserts);
    RUN_TEST(test_highscore_stress_100_descending_inserts);
    RUN_TEST(test_highscore_stress_alternating_inserts);
    RUN_TEST(test_highscore_invariant_sorted_descending);

    /* ========== Game Integration: Original ========== */
    RUN_TEST(test_game_init_sets_title_and_resets_counters);
    RUN_TEST(test_game_title_start_enters_running_and_steps_simulation);
    RUN_TEST(test_game_quit_input_has_priority);
    RUN_TEST(test_game_running_pause_freezes_simulation);
    RUN_TEST(test_game_paused_resume_reenters_running);
    RUN_TEST(test_game_survival_points_increment_once_per_second);
    RUN_TEST(test_game_survival_awards_multiple_seconds_for_large_dt_spec);
    RUN_TEST(test_game_pause_freezes_score_timers);
    RUN_TEST(test_game_over_screen_has_minimum_lock_before_highscores_spec);

    /* ========== Game Integration: Extended ========== */
    RUN_TEST(test_game_init_null_game_is_safe);
    RUN_TEST(test_game_init_null_config_is_safe);
    RUN_TEST(test_game_init_state_is_title);
    RUN_TEST(test_game_init_tick_count_zero);
    RUN_TEST(test_game_init_run_time_zero);
    RUN_TEST(test_game_init_fixed_steps_zero);
    RUN_TEST(test_game_init_second_fraction_zero);
    RUN_TEST(test_game_init_score_state_zeroed);
    RUN_TEST(test_game_init_highscore_table_zeroed);
    RUN_TEST(test_game_init_can_be_called_multiple_times);
    RUN_TEST(test_game_update_null_game_is_safe);
    RUN_TEST(test_game_update_null_input_is_safe);
    RUN_TEST(test_game_update_zero_dt_is_noop);
    RUN_TEST(test_game_update_negative_dt_is_noop);
    RUN_TEST(test_game_title_to_running_via_start);
    RUN_TEST(test_game_title_to_running_via_restart);
    RUN_TEST(test_game_title_to_quit);
    RUN_TEST(test_game_title_no_input_stays_title);
    RUN_TEST(test_game_running_to_paused);
    RUN_TEST(test_game_paused_to_running_via_resume);
    RUN_TEST(test_game_paused_to_running_via_pause_toggle);
    RUN_TEST(test_game_running_quit_from_running);
    RUN_TEST(test_game_paused_quit);
    RUN_TEST(test_game_quit_priority_over_start);
    RUN_TEST(test_game_quit_priority_over_pause);
    RUN_TEST(test_game_quit_priority_over_resume);
    RUN_TEST(test_game_quit_priority_over_restart);
    RUN_TEST(test_game_ticks_advance_in_running);
    RUN_TEST(test_game_ticks_frozen_in_title);
    RUN_TEST(test_game_ticks_frozen_in_paused);
    RUN_TEST(test_game_fixed_steps_track_ticks);
    RUN_TEST(test_game_second_fraction_accumulates);
    RUN_TEST(test_game_second_fraction_wraps_at_one);
    RUN_TEST(test_game_survival_point_awarded_at_one_second);
    RUN_TEST(test_game_no_survival_point_before_one_second);
    RUN_TEST(test_game_survival_accumulates_over_time);
    RUN_TEST(test_game_pause_freezes_tick_count);
    RUN_TEST(test_game_pause_freezes_second_fraction);
    RUN_TEST(test_game_pause_freezes_run_time);
    RUN_TEST(test_game_pause_freezes_combo_timer);
    RUN_TEST(test_game_resume_continues_from_paused_state);
    RUN_TEST(test_game_combo_timer_ticks_down_in_running);
    RUN_TEST(test_game_combo_expires_during_running);
    RUN_TEST(test_game_game_over_auto_transitions_to_highscores);
    RUN_TEST(test_game_highscores_restart_enters_running);
    RUN_TEST(test_game_highscores_start_enters_running);
    RUN_TEST(test_game_highscores_quit);
    RUN_TEST(test_game_highscores_no_input_stays);
    RUN_TEST(test_game_game_over_start_shows_highscores);
    RUN_TEST(test_game_game_over_restart_shows_highscores);
    RUN_TEST(test_game_game_over_quit);
    RUN_TEST(test_game_full_lifecycle_title_run_die_highscores_restart);
    RUN_TEST(test_game_full_lifecycle_title_run_pause_quit);
    RUN_TEST(test_game_quit_is_terminal);
    RUN_TEST(test_game_no_simulation_in_quit);
    RUN_TEST(test_input_direction_enum_values);
    RUN_TEST(test_game_rapid_start_pause_resume);
    RUN_TEST(test_game_multiple_no_input_updates);

    TEST_SUMMARY();
    return g_test_failures == 0 ? 0 : 1;
}
